"""Add location field to FAQ model

Revision ID: ec3bead05a27
Revises: a11cd6edc2f4
Create Date: 2025-07-01 17:43:37.526277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec3bead05a27'
down_revision: Union[str, Sequence[str], None] = 'a11cd6edc2f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faqs', sa.Column('location', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faqs', 'location')
    # ### end Alembic commands ###
